const Refs = {
  body: document.querySelector('body'),
  footer: document.querySelector('.footer'),
  movieStorage: document.querySelector('.js-movie__list'),
  studentGoit: document.querySelector('.text-company-link'),
  backdrop: document.querySelector('.backdrop-team'),
  team: document.querySelector('.team-modal'),
  btnClose: document.querySelector('.modal-close-btn'),
  paginationContainer: document.querySelector('.pagination-wrapper'),
  paginationList: document.querySelector('.pagination-list'),
  prevPageButton: document.querySelector('.prev-page-button'),
  nextPageButton: document.querySelector('.next-page-button'),
  totalPagesButton: document.querySelector('.total-button'),
  inputSearch: document.querySelector('.header__search-content input'),
  sliderWrapper: document.querySelector('.slider-wrapper'),
  sliderWrappeBtnLeft: document.querySelector('.glide__arrow--left'),
  sliderWrappeBtnRight: document.querySelector('.glide__arrow--right'),
  sliderContainer: document.querySelector('.js-slider-container'),
  themeSwitcher: document.querySelector('.theme__switch-toggle'),
  copyrightLogo: document.querySelector('.copyright-logo'),
  searchError: document.querySelector('.header__search-info'),
  movieModal: document.querySelector('.modal-card'),
  modalBtns: document.querySelector('.modal-card-button'),
  modalCardsCloseBtn: document.querySelector('.button-close'),
  backdropModalCard: document.getElementById('backdrop'),
  navigationButtons: document.querySelector('.header__navigation'),
  openHomepageButton: document.querySelector('.open-homepage'),
  openLibraryButton: document.querySelector('.open-library-button'),
  browseLibraryButtons: document.querySelector('.header__actions'),
  browseWatchedFilmsButton: document.querySelector('.watched-btn'),
  browseFilmsInQueueButton: document.querySelector('.queue-btn'),
  usersFilmsLibrary: document.querySelector('.js-library__list'),
};

export default Refs;
