import '/js/refs';
import './sass/main.scss';
import './js/students';
import './js/pagination';
import './js/components/header/header';
import './js/defaultPage';
import './js/theme-switch';
import './js/slider';
import './js/trailers';
import './js/back-to-top-btn'
